let _books = [
  {
    id: 0,
    name: "1984",
    url: "amazon.com",
    author: "George Orwell",
    author_url: "wikipedia.org",
    no_lists: 6,
    page_name: "1984",
  },
  {
    id: 1,
    name: "The Adventures of Huckleberry Finn",
    url: "amazon.com",
    author: "Mark Twain",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "adventures-of-huckleberry-finn",
  },
  {
    id: 2,
    name: "The Adventures of Pinocchio",
    url: "amazon.com",
    author: "Carlo Collodi",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "adventures-of-pinocchio",
  },
  {
    id: 3,
    name: "All Quiet on the Western Front",
    url: "amazon.com",
    author: "Erich Maria Remarque",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "all-quiet-on-the-western-front",
  },
  {
    id: 4,
    name: "The Analects",
    url: "amazon.com",
    author: "Confucius",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "analects",
  },
  {
    id: 5,
    name: "Animal Farm",
    url: "amazon.com",
    author: "George Orwell",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "animal-farm",
  },
  {
    id: 6,
    name: "Anna Karenina",
    url: "amazon.com",
    author: "Leo Tolstoy",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "anna-karenina",
  },
  {
    id: 7,
    name: "Anne of Green Gables",
    url: "amazon.com",
    author: "L. M. Montgomery",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "anne-of-green-gables",
  },

  {
    id: 8,
    name: "The Arabian Nights",
    url: "amazon.com",
    author: "",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "arabian-nights",
  },
  {
    id: 9,
    name: "The Art of War",
    url: "amazon.com",
    author: "Sun Zi",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "art-of-war",
  },
  {
    id: 10,
    name: "Autobiography of Benjamin Franklin",
    url: "amazon.com",
    author: "Benjamin Franklin",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "autobiography-of-benjamin-franklin",
  },
  {
    id: 11,
    name: "Beloved",
    url: "amazon.com",
    author: "Toni Morrison",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "beloved",
  },
  {
    id: 12,
    name: "Ben Hur: A Tale of Christ",
    url: "amazon.com",
    author: "Lew Wallace",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "ben-hur-a-tale-of-christ",
  },
  {
    id: 13,
    name: "Beyond Good and Evil: Prelude to a Philosophy of the Future",
    url: "amazon.com",
    author: "Friedrich Nietzsche",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "beyond-good-and-evil",
  },
  {
    id: 14,
    name: "Black Beauty",
    url: "amazon.com",
    author: "Anna Sewell",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "black-beauty",
  },
  {
    id: 15,
    name: "Brave New World",
    url: "amazon.com",
    author: "Aldous Huxley",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "brave-new-world",
  },
  {
    id: 16,
    name: "The Brothers Karamazov",
    url: "amazon.com",
    author: "Fyodor Dostoevsky",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "brothers-karamazov",
  },
  {
    id: 17,
    name: "The Canterbury Tales",
    url: "amazon.com",
    author: "Geoffrey Chaucer",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "canterbury-tales",
  },
  {
    id: 18,
    name: "Catch-22",
    url: "amazon.com",
    author: "Joseph Heller",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "catch-22",
  },
  {
    id: 19,
    name: "Charlotte's Web",
    url: "amazon.com",
    author: "E. B. White",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "charlottes-web",
  },
  {
    id: 20,
    name: "The Communist Manifesto",
    url: "amazon.com",
    author: "Karl Marx",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "communist-manifesto",
  },
  {
    id: 21,
    name: "The Complete Fairy Tales and Stories",
    url: "amazon.com",
    author: "Hans Christian Andersen",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "complete-fairy-tales-and-stories",
  },
  {
    id: 22,
    name: "The Complete Works of William Shakespeare",
    url: "amazon.com",
    author: "William Shakespeare",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "complete-works-of-william-shakespeare",
  },
  {
    id: 23,
    name: "Crime and Punishment",
    url: "amazon.com",
    author: "Fyodor Dostoevsky",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "crime-and-punishment",
  },
  {
    id: 24,
    name: "Democracy in America",
    url: "amazon.com",
    author: "Alexis de Tocqueville",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "democracy-in-america",
  },
  {
    id: 25,
    name: "Demons",
    url: "amazon.com",
    author: "Fyodor Dostoevsky",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "demons",
  },
  {
    id: 26,
    name: "The Diary of a Young Girl",
    url: "amazon.com",
    author: "Anne Frank",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "diary-of-a-young-girl",
  },
  {
    id: 27,
    name: "The Divine Comedy",
    url: "amazon.com",
    author: "Dante Alighieri",
    author_url: "wikipedia.org",
    no_lists: 5,
    page_name: "divine-comedy",
  },
  {
    id: 28,
    name: "Don Quixote",
    url: "amazon.com",
    author: "Miguel De Cervantes",
    author_url: "wikipedia.org",
    no_lists: 6,
    page_name: "don-quixote",
  },
  {
    id: 29,
    name: "Fahrenheit 451",
    url: "amazon.com",
    author: "Ray Bradbury",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "fahrenheit-451",
  },
  {
    id: 30,
    name: "Faust, First Part",
    url: "amazon.com",
    author: "Johann Wolfgang von Goethe",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "faust-first-part",
  },
  {
    id: 31,
    name: "The Federalist Papers",
    url: "amazon.com",
    author: "Alexander Hamilton",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "federalist-papers",
  },
  {
    id: 32,
    name: "For Whom the Bell Tolls",
    url: "amazon.com",
    author: "Ernest Hemingway",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "for-whom-the-bell-tolls",
  },
  {
    id: 33,
    name: "Frankenstein",
    url: "amazon.com",
    author: "Mary Shelley",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "frankenstein",
  },
  {
    id: 34,
    name: "The Godfather",
    url: "amazon.com",
    author: "Mario Puzo",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "godfather",
  },
  {
    id: 35,
    name: "The Grapes of Wrath",
    url: "amazon.com",
    author: "John Steinbeck",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "grapes-of-wrath",
  },
  {
    id: 36,
    name: "Great Expectations",
    url: "amazon.com",
    author: "Charles Dickens",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "great-expectations",
  },
  {
    id: 37,
    name: "The Great Gasby",
    url: "amazon.com",
    author: "F. Scott Fitzgerald",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "great-gatsby",
  },
  {
    id: 38,
    name: "Grimm's Fairy Tales",
    url: "amazon.com",
    author: "Jacob Grimm",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "grimms-fairy-tales",
  },
  {
    id: 39,
    name: "The Gulag Archipelago",
    url: "amazon.com",
    author: "Aleksandr Solzhenitsyn",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "gulag-archipelago",
  },
  {
    id: 40,
    name: "Gulliver's Travels",
    url: "amazon.com",
    author: "Johnathan Swift",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "gullivers-travels",
  },
  {
    id: 41,
    name: "Heidi",
    url: "amazon.com",
    author: "Johanna Spyri",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "hamlet",
  },
  {
    id: 42,
    name: "How to Win Friends and Influence People",
    url: "amazon.com",
    author: "Dale Carnegie",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "how-to-win-friends-and-influence-people",
  },
  {
    id: 43,
    name: "The Hobbit",
    url: "amazon.com",
    author: "J. R. R. Tolkien",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "hobbit",
  },
  {
    id: 44,
    name: "The Holy Bible",
    url: "amazon.com",
    author: "",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "holy-bible",
  },
  {
    id: 45,
    name: "The Idiot",
    url: "amazon.com",
    author: "Fyodor Dostoevsky",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "idiot",
  },
  {
    id: 46,
    name: "The Iliad",
    url: "amazon.com",
    author: "Homer",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "iliad",
  },
  {
    id: 47,
    name: "In Search of Lost Time",
    url: "amazon.com",
    author: "Marcel Proust",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "in-search-of-lost-time",
  },
  {
    id: 48,
    name: "Invisible Man",
    url: "amazon.com",
    author: "Ralph Ellison",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "invisible-man",
  },
  {
    id: 49,
    name: "Jane Eyre",
    url: "amazon.com",
    author: "Charlotte Bronte",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "jane-eyre",
  },
  {
    id: 50,
    name: "The Last Mohicans",
    url: "amazon.com",
    author: "James Fenimore Cooper",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "last-of-the-mohicans",
  },
  {
    id: 51,
    name: "Les Miserables",
    url: "amazon.com",
    author: "Victor Hugo",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "les-miserables",
  },
  {
    id: 52,
    name: "Leviathan",
    url: "amazon.com",
    author: "Thomas Hobbes",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "leviathan",
  },
  {
    id: 53,
    name: "Life of Frederick Douglass, an American Slave",
    url: "amazon.com",
    author: "Frederick Douglass",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "life-of-frederick-douglass-an-american-slave",
  },
  {
    id: 54,
    name: "Lives of the Noble Grecians and Romans",
    url: "amazon.com",
    author: "Plutarch",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "lives-of-the-noble-grecians-and-romans",
  },
  {
    id: 55,
    name: "Lolita",
    url: "amazon.com",
    author: "Vladimir Nabokov",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "lolita",
  },
  {
    id: 56,
    name: "The Long Goodbye",
    url: "amazon.com",
    author: "Raymond Chandler",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "long-goodbye",
  },
  {
    id: 57,
    name: "Lord of the Flies",
    url: "amazon.com",
    author: "William Golding",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "lord-of-the-flies",
  },
  {
    id: 58,
    name: "The Lord of the Rings",
    url: "amazon.com",
    author: "J. R. R. Tolkien",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "lord-of-the-rings",
  },
  {
    id: 59,
    name: "Madame Bovary",
    url: "amazon.com",
    author: "Gustave Flaubert",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "madame-bovary",
  },
  {
    id: 60,
    name: "The Maltese Falcon",
    url: "amazon.com",
    author: "Dashiell Hammett",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "maltese-falcon",
  },
  {
    id: 61,
    name: "Man's Search for Meaning",
    url: "amazon.com",
    author: "Viktor Frankl",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "mans-search-for-meaning",
  },
  {
    id: 62,
    name: "The Master and Margarita",
    url: "amazon.com",
    author: "Mikhail Bulgakov",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "master-and-margarita",
  },
  {
    id: 63,
    name: "Meditations",
    url: "amazon.com",
    author: "Marcus Aurelius",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "meditations",
  },
  {
    id: 64,
    name: "Moby Dick",
    url: "amazon.com",
    author: "Herman Melville",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "moby-dick",
  },
  {
    id: 65,
    name: "Mrs. Dalloway",
    url: "amazon.com",
    author: "Virginia Woolf",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "mrs-dalloway",
  },
  {
    id: 67,
    name: "Native Son",
    url: "amazon.com",
    author: "Richard Wright",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "native-son",
  },
  {
    id: 68,
    name: "The Nicomachean Ethics",
    url: "amazon.com",
    author: "Aristotle",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "nicomachean-ethics",
  },
  {
    id: 69,
    name: "The Odyssey",
    url: "amazon.com",
    author: "Homer",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "odyssey",
  },
  {
    id: 70,
    name: "The Oedipus Trilogy",
    url: "amazon.com",
    author: "Sophocles",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "oedipus-trilogy",
  },
  {
    id: 71,
    name: "The Old Man and the Sea",
    url: "amazon.com",
    author: "Ernest Hemingway",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "old-man-and-the-sea",
  },
  {
    id: 72,
    name: "On Liberty",
    url: "amazon.com",
    author: "John Stuart Mill",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "on-liberty",
  },
  {
    id: 73,
    name: "On the Duty of Civil Disobedience",
    url: "amazon.com",
    author: "Henry David Thoreau",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "on-the-duty-of-civil-disobedience",
  },
  {
    id: 74,
    name: "One Hundred Years of Solitude",
    url: "amazon.com",
    author: "Gabriel Garcia Marquez",
    author_url: "wikipedia.org",
    no_lists: 5,
    page_name: "one-hundred-years-of-solitude",
  },
  {
    id: 75,
    name: "The Outsiders",
    url: "amazon.com",
    author: "S. E. Hinton",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "outsiders",
  },
  {
    id: 76,
    name: "The Principia: Mathematical Principles of Natural Philosophy",
    url: "amazon.com",
    author: "Isaac Newton",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "principia",
  },
  {
    id: 77,
    name: "Pride and Prejudice",
    url: "amazon.com",
    author: "Jane Austen",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "pride-and-prejudice",
  },
  {
    id: 78,
    name: "The Prince",
    url: "amazon.com",
    author: "Niccolo Machiavelli",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "prince",
  },
  {
    id: 79,
    name: "The Red and the Black",
    url: "amazon.com",
    author: "Stendhal",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "red-and-the-black",
  },
  {
    id: 80,
    name: "The Republic",
    url: "amazon.com",
    author: "Plato",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "republic",
  },
  {
    id: 81,
    name: "Robinson Crusoe",
    url: "amazon.com",
    author: "Daniel Defoe",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "robinson-crusoe",
  },
  {
    id: 82,
    name: "The Seven Habits of Highly Effective People",
    url: "amazon.com",
    author: "Stephen R. Covey",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "seven-habits-of-highly-effective-people",
  },
  {
    id: 83,
    name: "The Stranger",
    url: "amazon.com",
    author: "Albert Camus",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "stranger",
  },
  {
    id: 84,
    name: "The Swiss Family Robinson",
    url: "amazon.com",
    author: "Johann Davide Wyss",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "swiss-family-robinson",
  },
  {
    id: 85,
    name: "The Tale of Genji",
    url: "amazon.com",
    author: "Murasaki Shikibu",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "tale-of-genji",
  },
  {
    id: 86,
    name: "A Tale of Two Cities",
    url: "amazon.com",
    author: "Charles Dickens",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "tale-of-two-cities",
  },
  {
    id: 87,
    name: "Things Fall Apart",
    url: "amazon.com",
    author: "Chinua Achebe",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "things-fall-apart",
  },
  {
    id: 88,
    name: "To Kill a Mockingbird",
    url: "amazon.com",
    author: "Harper Lee",
    author_url: "wikipedia.org",
    no_lists: 4,
    page_name: "to-kill-a-mockingbird",
  },
  {
    id: 89,
    name: "Treasure Island",
    url: "amazon.com",
    author: "Robert Louis Stevenson",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "treasure-island",
  },
  {
    id: 90,
    name: "Ulysses",
    url: "amazon.com",
    author: "James Joyce",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "ulysses",
  },
  {
    id: 91,
    name: "Uncle Tom's Cabin",
    url: "amazon.com",
    author: "Harriet Beecher Stowe",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "uncle-toms-cabin",
  },
  {
    id: 92,
    name: "War and Peace",
    url: "amazon.com",
    author: "Leo Tolstoy",
    author_url: "wikipedia.org",
    no_lists: 5,
    page_name: "war-and-peace",
  },
  {
    id: 93,
    name: "The Wealth of Nations",
    url: "amazon.com",
    author: "Adam Smith",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "wealth-of-nations",
  },
  {
    id: 94,
    name: "The Wind in the Willows",
    url: "amazon.com",
    author: "Kenneth Grahame",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "wind-in-the-willows",
  },
  {
    id: 95,
    name: "Wuthering Heights",
    url: "amazon.com",
    author: "Emily Brontë",
    author_url: "wikipedia.org",
    no_lists: 3,
    page_name: "wuthering-heights",
  },
  {
    id: 96,
    name: "Zen and the Art of Motorcycle Maintenance",
    url: "amazon.com",
    author: "Robert Pirsig",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "zen-and-the-art-of-motorcycle-maintenance",
  },
  {
    id: 97,
    name: "Zorba the Greek",
    url: "amazon.com",
    author: "Nikos Kazantzakis",
    author_url: "wikipedia.org",
    no_lists: 2,
    page_name: "zorba-the-greek",
  },
];

module.exports = {
  books: _books,
  getBookById: (id) => _books.filter((book) => book.id === id * 1)[0],
  getBook: (page_name) =>
    _books.filter((book) => book.page_name === page_name)[0],
  getBookByNoList: () =>
    _books.reduce(function (r, a) {
      r[a.no_lists] = r[a.no_lists] || [];
      r[a.no_lists].push(a);
      return r;
    }, Object.create(null)),
  getBookSortByName: () =>
    _books.sort((a, b) => {
      if (a.name < b.name) {
        return -1;
      }
      if (a.name > b.name) {
        return 1;
      }
      return 0;
    }),
};
